title: "Arjun Badola"
author: "Arjun Badola"
description: "Writing ∝ Reading"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: ""

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header
show_related: true          # show the previous and next links after every post

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "threads.md"}
  - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Twitter, icon: twitter, url: "https://twitter.com/badola_arjun"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/arjunbadola/"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
